course/course/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views


urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('account/', views.accountPageView, name='account'),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

course/movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainPageView.as_view(), name='main'),
    path('movies/', views.moviePageView.as_view(), name='movies'),
    path('cartoons/', views.cartoonsPageView.as_view(), name='cartoons'),
    path('serials/', views.serialsPageView.as_view(), name='serials'),
    path('anime/', views.animePageView.as_view(), name='anime'),
    path('movie/<int:pk>/', views.movieDetailView.as_view(), name='detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('<int:pk>/edit', views.ReviewUpdateView.as_view(), name='review_edit'),
    path('<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review_delete')
]

course/users/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('registration/', views.Signup.as_view(), name='registration'),
]

course/movies/models.py
from datetime import date
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse


class Actor(models.Model):
    name = models.CharField("Имя", max_length=100)
    date_of_birth = models.DateField("Дата рождения", default=date.today)
    image = models.ImageField("Изображение", upload_to="static/actors/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актёры и режиссёры"
        verbose_name_plural = "Актёры и режиссёры"

class Genre(models.Model):
    name = models.CharField("Жанр", max_length=100)
    # url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="static/poster/")
    banner = models.ImageField("Банер", upload_to="static/banner/")
    video = models.FileField(upload_to="static/video/", default="cat.mp4")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2022)
    country = models.CharField("Страна", max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name="Режиссёр", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="Актёры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    budget = models.PositiveSmallIntegerField("Бюджет", default=0, help_text="Сумма в долларах")
    fees_in_usa = models.PositiveSmallIntegerField("Сборы в США", default=0, help_text="Сумма в долларах")
    fees_in_world = models.PositiveSmallIntegerField("Сборы в мире", default=0, help_text="Сумма в долларах")
    promo = models.BooleanField("Промо", default=False)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class Reviews(models.Model):
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Комментарий", max_length=2000)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('detail')

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

course/users/models.py
from django.db import models

# Create your models here.

course/movies/forms.py
from django import forms
from .models import Reviews

class ReviwForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("name", "text")

course/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

course/movies/views.py
from . import models
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Movie, Reviews
from .forms import ReviwForm
from django.db.models import Q

class mainPageView(ListView):
    model = Movie
    template_name = "main.html"

class moviePageView(ListView):
    model = Movie
    template_name = "movies.html"

class cartoonsPageView(ListView):
    model = Movie
    template_name = "cartoons.html"

class serialsPageView(ListView):
    model = Movie
    template_name = "serials.html"

class animePageView(ListView):
    model = Movie
    template_name = "anime.html"

class movieDetailView(DetailView):
    model = Movie
    template_name = "detail.html"

class AddReview(View):
    def post(self, request, pk):
        form = ReviwForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie_id = pk
            form.save()
        return redirect("/")

class ReviewUpdateView(UpdateView):
    model = Reviews
    template_name = 'review_edit.html'
    fields = ['text']
    success_url = reverse_lazy('main')
class ReviewDeleteView(DeleteView):
    model = Reviews
    template_name = 'review_delete.html'
    success_url = reverse_lazy('main')

course/pages/views.py
from django.shortcuts import render



def mainPageView(request):
    return render(request, "main.html")

def filmsPageView(request):
    return render(request, "movies.html")

def cartoonsPageView(request):
    return render(request, "cartoons.html")

def serialsPageView(request):
    return render(request, "serials.html")

def animePageView(request):
    return render(request, "anime.html")

def accountPageView(request):
    return render(request, "account.html")

course/users/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from .forms import UserCreationForm

class Signup(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration.html'

course/templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="container">
    <div class="auth_buttons">
      {% if user.is_authenticated %}
      <a class="button" href="{% url 'logout' %}">Выйти</a>
      {% else %}
      <ul>
        <li><a class="button" href="{% url 'login' %}">Войти</a></li>
        <li><a class="button" href="{% url 'registration' %}">Зарегистрироваться</a></li>
      </ul>
      {% endif %}
    </div>

  </div>

{% endblock %}

course/templates/anime.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
  <title>Kinostock</title>
</head>
<body>
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    {% endblock %}
</body>
</html>

course/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Video.js base CSS -->
  <link
    href="https://unpkg.com/video.js@7/dist/video-js.min.css"
    rel="stylesheet"
  />

  <!-- City -->
  <link
    href="https://unpkg.com/@videojs/themes@1/dist/city/index.css"
    rel="stylesheet"
  />

  <title>Kinostock</title>
</head>
<body class="wrapper">
  <header>
    <div class="container">
      <nav>
        <ul>
          <li><a href="{% url 'main' %}"><h1 class="logo">Kinostock</h1></a></li>
<!--          <li><a href="{% url 'movies' %}">Фильмы</a></li>-->
<!--          <li><a href="{% url 'serials' %}">Сериалы</a></li>-->
<!--          <li><a href="{% url 'cartoons' %}">Мультфильмы</a></li>-->
<!--          <li><a href="{% url 'anime' %}">Аниме</a></li>-->
        </ul>
      </nav>
      <ul>
<!--        <li><a href="#">Поиск</a></li>-->
        <li><a href="{% url 'account' %}">Аккаунт</a></li>
      </ul>
    </div>
  </header>

{% block content %}

{% endblock %}
</body>
<script src="{% static 'JS/script.js' %}"></script>
<script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
</html>

course/templates/cartoons.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
  <title>Kinostock</title>
</head>
<body>
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    {% endblock %}
</body>
</html>

course/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div style="margin-top: 130px; padding-top: 40px;" class="borders-section">
      <div class="container">
          <div style="display: flex;">

              <div class="image-block">
                  <img src="{{ movie.poster.url }}" alt="">
              </div>

              <div class="description">
                  <h2 style="margin-top: 0px; margin-bottom: 25px;">{{ movie.title }}</h2>

                  <p>{{ movie.description }}</p>

                  <p>Год производства: {{ movie.year }}</p>

                  <p>Жанр:
                      {% for genre in movie.genres.all %}
                      {{ genre.name }}
                      {% endfor %}
                  </p>

                  <p>Страна: {{ movie.country }}</p>

                  <p>Бюджет: {{ movie.budget }}$</p>

                  <p>Сборы в США: {{ movie.fees_in_usa }}$</p>

                  <p>Сборы в мире: {{ movie.fees_in_world }}</p>
              </div>
          </div>
      </div>
  </div>

  <div class="video">
      {% if user.is_authenticated %}
      <video controls width="100%" height="700px">
          <source src="{{ movie.video.url }}">
      </video>
      {% else %}
      <h3 style=" text-align: center; padding-top: 300px;">Для доступа к фильму войдите в аккаунт</h3>
      {% endif %}
  </div>

  <div style="padding-top: 40px;" class="borders-section">
      <div class="container">
          <h3>Режиссёры:</h3>

          <div class="actors-list">
              {% for director in movie.directors.all %}
              <div class="actor">
                  <img class="actor-img" src="{{ director.image.url }}">
                  <p>
                      {{ director.name }}
                  </p>
              </div>
              {% endfor %}
          </div>

          <h3>Актёры:</h3>

          <div class="actors-list">
              {% for actor in movie.actors.all %}
              <div class="actor">
                  <img class="actor-img" src="{{ actor.image.url }}">
                  <p>
                      {{ actor.name }}
                  </p>
              </div>
              {% endfor %}
          </div>
      </div>
  </div>

  <div class="container">
      <div class="comments">
          <h3>Написать комментарий:</h3>

          {% if user.is_authenticated %}

          <form style="margin-top: 50px; margin-bottom : 50px;" action="{% url 'add_review' movie.id %}" method="post">
              {% csrf_token %}
              <textarea style="margin-bottom: 20px;" rows="8" cols="60" name="text" required="" placeholder="Текст комментария..."></textarea>
              <div style="display: flex;">
                  <div style="margin-right: 40px;">
                      <input type="text" name="name" required="" value="{{ user.username }}" readonly>
                  </div>
              </div>
              <button style="margin-top: 20px; margin-left: 0px;" type="submit">Отправить</button>
          </form>

          {% else %}
          <h3>Чтобы оставить комментарий войдите в аккаунт</h3>
          {% endif %}
          <h3>Комментарии:</h3>
          {% for review in movie.reviews_set.all %}
          <div class="reviews">
              <div class="review" style="flex-direction: column; margin-bottom: 20px;">
                  <p style="margin-bottom: 0px; color: rgb(220, 220, 220); "> {{ review.name }}: </p>
                  <p style="margin-bottom: 0px; ">{{ review.text }}</p>
                  {% if review.name == user.username %}
                      <p>
                          <a href="{% url 'review_edit' review.pk %}">Редактировать</a> |
                          <a href="{% url 'review_delete' review.pk %}">Удалить</a>
                      </p>
                  {% endif %}
              </div>
          </div>

          {% endfor %}
      </div>
  </div>


{% endblock %}

course/templates/films.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
  <title>Kinostock</title>
</head>
<body>
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    {% endblock %}
</body>
</html>

course/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <main>

    <div class="carousel-3d" data-gap="20" data-bfc>
        <figure>
            {% for movie in object_list %}
                {% if movie.promo == True %}
                    <div><a href="{% url 'detail' movie.pk %}"><img class="carousel-3d-border" src="{{ movie.banner }}"></a></div>yyyyy
                {% endif %}
            {% endfor %}
        </figure>
        <nav>
            <button class="nav prev">Назад</button>
            <button class="nav next">Вперед</button>
        </nav>
    </div>

    <div class="borders-section">

        <div class="container">
            <h3>Все фильмы</h3>
            <ul class="films-list">
                {% for movie in object_list %}
                <li><a href="{% url 'detail' movie.pk %}"><img src="{{ movie.poster }}"></a></li>
                {% endfor %}
            </ul>
        </div>

    </div>

  </main>

{% endblock %}

course/templates/movies.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
  <title>Kinostock</title>
</head>
<body>
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    {% endblock %}
</body>
</html>

course/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container auth_page">
    <form method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <div class="form-group"><button style="margin-left: 0px; margin-top: 10px;" class="button btn btn-primary btn-block" type="submit">Зарегистрироваться</button></div>
    </form>
</div>

{% endblock %}

course/templates/review_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Удалить</h2>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <p>Удалить комментарий?</p>
        <button style="margin-top: 20px; margin-left: 0px;" type="submit">Удалить</button>
    </form>
</div>
{% endblock %}

course/templates/review_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Редактировать</h2>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button style="margin-top: 20px; margin-left: 0px;" type="submit">Обновить</button>
    </form>
</div>

{% endblock %}

course/templates/serials.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% endblock %}